MVC4LOL/Controllers/ChampionController.cs
using MVC4LOL.Model;
using MVC4LOL.Models;
using MVC4LOL.Models.ViewModels;
using MVC4LOL.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace MVC4LOL.Controllers
{
    [Authorize]
    public class ChampionController : Controller
    {
        private MVC4LOLDb _cx { get; set; }
        public ChampionController()
        {
            if (_cx == null)
            {
                _cx = new MVC4LOLDb();
            }
        }

        // Not used anymore. TODO DELETE.
        //public ActionResult Index()
        //{
        //    var model = new ChampionsViewModel();
        //    model.Patches = _cx.PatchVersions.ToList();

        //    Int32 latestPatchId = model.Patches.OrderByDescending(p => p.Date).First().Id;
        //    model.Champions = _cx.ChampionData
        //                         .Where(o => o.PatchVersionId == latestPatchId)
        //                         .ToList();

        //    // Test if Tags are unique
        //    //model.Tags = _cx.Tags.Where(o => o.UserId == userId).GroupBy(o => o.Name).Select(o => o.Key).ToList();
        //    model.Tags = _cx.Tags.Where(o => o.UserId == WebSecurity.CurrentUserId).ToList();
        //    return View(model);
        //}

        public ActionResult Details(String name)
        {
            Int32 championId = _cx.Champions.FirstOrDefault(o => o.Name.Equals(name)).Id;
            
            var model = new ChampionDetailsViewModel();

            model.Patches = _cx.PatchVersions.ToList();
            Int32 latestPatchId = model.Patches.OrderByDescending(o => o.Date).First().Id;
            model.SelectedPatchId = latestPatchId;

            model.Tags = _cx.Tags.Where(o => o.UserId == WebSecurity.CurrentUserId && o.ChampionId == championId).ToList();
            model.Champions = _cx.ChampionData.Where(o => o.ChampionId == championId).ToList();

            return View("Details", model);
        }

        //TODO: combine both details actions
        public ActionResult Details2(Int32 championId)
        {
            var model = new ChampionDetailsViewModel();

            model.Patches = _cx.PatchVersions.ToList();
            Int32 latestPatchId = model.Patches.OrderByDescending(o => o.Date).First().Id;
            model.SelectedPatchId = latestPatchId;

            model.Tags = _cx.Tags.Where(o => o.UserId == WebSecurity.CurrentUserId && o.ChampionId == championId).ToList();
            model.Champions = _cx.ChampionData.Where(o => o.ChampionId == championId).ToList();
            
            return View("Details", model);
        }

        public ActionResult Tags(Int32 championId)
        {
            TagsViewModel model = new TagsViewModel();
            model.Tags = _cx.Tags.Where(o => o.ChampionId == championId && o.UserId == WebSecurity.CurrentUserId).ToList();
            model.Champion = _cx.Champions.Find(championId);
            return View("Tags", model);
        }

        [HttpGet]
        public ActionResult CreateTag(Int32 championId)
        {
            var modelView = new EditTagsViewModel();
            modelView.ChampionId = championId;
            return View("CreateTag", modelView);
        }

        [HttpPost]
        public ActionResult CreateTag(EditTagsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Tag tag = new Tag();
                tag.ChampionId = model.ChampionId; 
                tag.UserId = WebSecurity.CurrentUserId;
                tag.Name = model.Name;

                _cx.Tags.Add(tag);
                _cx.SaveChanges();
                return Tags(model.ChampionId);
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult DeleteTag(Int32 tagId)
        {
            Tag tag = _cx.Tags.First(o => o.Id == tagId);
            _cx.Tags.Remove(tag);
            _cx.SaveChanges();
            return Tags(tag.ChampionId);
        }

        public ActionResult GetPhoto(int photoId)
        {
            byte[] photo = _cx.ChampionData.First(c => c.Id == photoId).Image;
            return photo != null ? File(photo, "image/jpeg") : (ActionResult)(null);
        }

        public ActionResult GetPhotoLastPatch(int photoId)
        {
            Int32 latestPatchId = _cx.PatchVersions.OrderByDescending(o => o.Date).First().Id; 
            byte[] photo = _cx.ChampionData.First(c => c.ChampionId == photoId && c.PatchVersionId == latestPatchId).Image;
            return photo != null ? File(photo, "image/jpeg") : (ActionResult)(null);
        }
    }
}

MVC4LOL/Controllers/CrawlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC4LOL.CRAWLER;

using MVC4LOL.Models;
using System.Data.Entity;
using System.Dynamic;
using System.Web.Routing;
using MVC4LOL.Helpers;
using MVC4LOL.Models.ViewModels;

namespace MVC4LOL.Controllers
{
    //[Authorize(Roles="Admin")]
    public class CrawlerController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Wikia()
        {
            MVC4LOL.CRAWLER.Wikia.HarvestData();
            return View();
        }

        public ActionResult ItemsWikia()
        {
            MVC4LOL.CRAWLER.ItemsWikia.HarvestData();
            return Content("DONE!!"); 
        }

    }
}

MVC4LOL/Controllers/ItemController.cs
using MVC4LOL.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC4LOL.Controllers
{
    public class ItemController : Controller
    {
        private MVC4LOLDb db = new MVC4LOLDb();
        public ActionResult Index()
        {
            var model = db.Items.ToList();
            return View("Index", model);
        }
        public ActionResult GetItemImage(int itemId)
        {
            byte[] image = db.Items.First(c => c.Id == itemId).Image;
            return image != null ? File(image, "image/jpeg") : (ActionResult)(null);
        }

    }
}

MVC4LOL/Controllers/PatchController.cs
using MVC4LOL.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC4LOL.Controllers
{
    public class PatchController : Controller
    {
        private  MVC4LOLDb _uc;

        public PatchController()
        {
            if (_uc == null)
            {
                _uc = new MVC4LOLDb();
            }
        }

        public PatchController(MVC4LOLDb dbContext)
        {
            if (_uc == null)
            {
                _uc = dbContext;
            }
        }

        public ActionResult Index()
        {
            // todo: add viewmodel
            var model = _uc.PatchVersions.ToList();
            return View(model);
        }
    }
}

MVC4LOL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

        @*<script src="@Url.Content("~/Scripts/Libs/jquery-1.9.1.js")" type="text/javascript" ></script>*@
        <script src="@Url.Content("~/Scripts/startup.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/dataservice.js")" type="text/javascript"></script>
        @*<script src="@Url.Content("~/Scripts/jQuery.tmpl.js")" type="text/javascript" ></script>
        <script src="@Url.Content("~/Templates/ChampionTemplate.html")" type="text/x-jquery-tmpl"></script>*@

        @*<script src="@Url.Content("~/Scripts/Libs/jquery-1.9.1.js")" type="text/javascript" ></script>
        <script src="@Url.Content("~/Scripts/Libs/jquery-ui-1.10.1.js")" type="text/javascript" ></script>
        <script src="@Url.Content("~/Scripts/Libs/jQuery.tmpl.js")" type="text/javascript" ></script>

        <script src="@Url.Content("~/Scripts/Libs/startup.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/Libs/dataservice.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Templates/ChampionTemplate.html")" type="text/x-jquery-tmpl"></script>*@

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/jquerytmpl")
        @Styles.Render("~/Content/themes/base/css")
        
        @*<link rel="stylesheet" href="@Url.Content("~/Content/themes/base/jquery.ui.button.css")" />*@


    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            @*<li>@Html.ActionLink("Champions", "Champions", "Home")</li>*@
                            @*<li>@Html.ActionLink("Champions", "Index", "Champion")</li>*@
                            <li>@Html.ActionLink("Champions", "Index2", "ChampionJson")</li>
                            <li>@Html.ActionLink("Items", "Index", "Item")</li>
                            <li>@Html.ActionLink("Patches", "Index", "Patch")</li>
                            <li>@Html.ActionLink("Crawlers", "Index", "Crawler")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>
        @RenderSection("scripts", required: false)
    </body>
</html>