MVC4LOL/Models/Champion.cs
//using System;
//using System.Collections.Generic;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//using System.Data.Entity;
//using System.Linq;
//using System.Web;

//namespace MVC4LOL.Models
//{
//    [Table("Champion")]
//    public class Champion
//    {
//        [Key]
//        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
//        public Int32 Id { get; set; }
//        public String Name { get; set; }
//        public String Title { get; set; }
//        public Byte[] Image { get; set; }
        
//        [DataType(DataType.Date)]
//        public DateTime ReleaseDate { get; set; }
        
//        public Int32 IP_Cost { get; set; }
//        public Int32 RP_Cost { get; set; }
//        public virtual List<Tag> Tags { get; set; }
//        public Decimal Health { get; set; }
//        public Decimal HealthPerLvl { get; set; }
//        public Decimal HealthRegen { get; set; }
//        public Decimal HealthRegenPerLvl { get; set; }
//        public Decimal Mana { get; set; }
//        public Decimal ManaPerLvl { get; set; }
//        public Decimal ManaRegen { get; set; }
//        public Decimal ManaRegenPerLvl { get; set; }
//        public Decimal Range { get; set; }
//        public Decimal Damage { get; set; }
//        public Decimal DamagePerLvl { get; set; }
//        public Decimal AttackSpeed { get; set; }
//        public Decimal AtsSpeedPerLvl { get; set; }
//        public Decimal Armor { get; set; }
//        public Decimal ArmorPerLvl { get; set; }
//        public Decimal MagicResist { get; set; }
//        public Decimal MagicResistPerLvl { get; set; }
//        public Decimal MoveSpeed { get; set; }

//        public virtual List<Skill> Skills { get; set; }

        
//        //public String Patch { get; set; }
//    }

//    [Table("Tag")]
//    public class Tag
//    {
//        public Int32 Id { get; set; }
//        public String Name { get; set; }
        
//        public Int32 UserId { get; set; } 
//        public virtual UserProfile UserProfile { get; set; }
//        public Int32 ChampionId { get; set; }
//        public virtual Champion Champion { get; set; }
//    }

//    [Table("Skill")]
//    public class Skill
//    {
//        public Int32 Id { get; set; }
//        public String Name { get; set; }
//        public Int32 Lvl { get; set; }
//        public String Description { get; set; }

//        public Int32 ChampionId { get; set; }
//        public virtual Champion Champion { get; set; }
//    }

//    // TODO : moved to AccountModels
//    //public class MVC4LOLContext : DbContext
//    //{
//    //    public MVC4LOLContext()
//    //        : base("DefaultConnection")
//    //    {
//    //    }

//    //    DbSet<Champion> Champions { get; set; }
//    //}

//}

MVC4LOL/Models/ViewModels/ChampionsViewModel.cs
using MVC4LOL.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC4LOL.Models.ViewModels
{
    public class ChampionsViewModel
    {
        public List<ChampionData> Champions { get; set; }
        public List<Tag> Tags { get; set; }
        public List<PatchVersion> Patches { get; set; }
    }
}

MVC4LOL/Models/ViewModels/TagsViewModel.cs
using MVC4LOL.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC4LOL.Models.ViewModels
{
    public class TagsViewModel
    {
        public List<Tag> Tags { get; set; }
        public Champion Champion { get; set; }
    }
}

MVC4LOL/Controllers/ChampionController.cs
using MVC4LOL.Model;
using MVC4LOL.Models;
using MVC4LOL.Models.ViewModels;
using MVC4LOL.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace MVC4LOL.Controllers
{
    [Authorize]
    public class ChampionController : Controller
    {
        private MVC4LOLDb _cx { get; set; }
        public ChampionController()
        {
            if (_cx == null)
            {
                _cx = new MVC4LOLDb();
            }
        }

        // Not used anymore. TODO DELETE.
        //public ActionResult Index()
        //{
        //    var model = new ChampionsViewModel();
        //    model.Patches = _cx.PatchVersions.ToList();

        //    Int32 latestPatchId = model.Patches.OrderByDescending(p => p.Date).First().Id;
        //    model.Champions = _cx.ChampionData
        //                         .Where(o => o.PatchVersionId == latestPatchId)
        //                         .ToList();

        //    // Test if Tags are unique
        //    //model.Tags = _cx.Tags.Where(o => o.UserId == userId).GroupBy(o => o.Name).Select(o => o.Key).ToList();
        //    model.Tags = _cx.Tags.Where(o => o.UserId == WebSecurity.CurrentUserId).ToList();
        //    return View(model);
        //}

        public ActionResult Details(String name)
        {
            Int32 championId = _cx.Champions.FirstOrDefault(o => o.Name.Equals(name)).Id;
            
            var model = new ChampionDetailsViewModel();

            model.Patches = _cx.PatchVersions.ToList();
            Int32 latestPatchId = model.Patches.OrderByDescending(o => o.Date).First().Id;
            model.SelectedPatchId = latestPatchId;

            model.Tags = _cx.Tags.Where(o => o.UserId == WebSecurity.CurrentUserId && o.ChampionId == championId).ToList();
            model.Champions = _cx.ChampionData.Where(o => o.ChampionId == championId).ToList();

            return View("Details", model);
        }

        //TODO: combine both details actions
        public ActionResult Details2(Int32 championId)
        {
            var model = new ChampionDetailsViewModel();

            model.Patches = _cx.PatchVersions.ToList();
            Int32 latestPatchId = model.Patches.OrderByDescending(o => o.Date).First().Id;
            model.SelectedPatchId = latestPatchId;

            model.Tags = _cx.Tags.Where(o => o.UserId == WebSecurity.CurrentUserId && o.ChampionId == championId).ToList();
            model.Champions = _cx.ChampionData.Where(o => o.ChampionId == championId).ToList();
            
            return View("Details", model);
        }

        public ActionResult Tags(Int32 championId)
        {
            TagsViewModel model = new TagsViewModel();
            model.Tags = _cx.Tags.Where(o => o.ChampionId == championId && o.UserId == WebSecurity.CurrentUserId).ToList();
            model.Champion = _cx.Champions.Find(championId);
            return View("Tags", model);
        }

        [HttpGet]
        public ActionResult CreateTag(Int32 championId)
        {
            var modelView = new EditTagsViewModel();
            modelView.ChampionId = championId;
            return View("CreateTag", modelView);
        }

        [HttpPost]
        public ActionResult CreateTag(EditTagsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Tag tag = new Tag();
                tag.ChampionId = model.ChampionId; 
                tag.UserId = WebSecurity.CurrentUserId;
                tag.Name = model.Name;

                _cx.Tags.Add(tag);
                _cx.SaveChanges();
                return Tags(model.ChampionId);
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult DeleteTag(Int32 tagId)
        {
            Tag tag = _cx.Tags.First(o => o.Id == tagId);
            _cx.Tags.Remove(tag);
            _cx.SaveChanges();
            return Tags(tag.ChampionId);
        }

        public ActionResult GetPhoto(int photoId)
        {
            byte[] photo = _cx.ChampionData.First(c => c.Id == photoId).Image;
            return photo != null ? File(photo, "image/jpeg") : (ActionResult)(null);
        }

        public ActionResult GetPhotoLastPatch(int photoId)
        {
            Int32 latestPatchId = _cx.PatchVersions.OrderByDescending(o => o.Date).First().Id; 
            byte[] photo = _cx.ChampionData.First(c => c.ChampionId == photoId && c.PatchVersionId == latestPatchId).Image;
            return photo != null ? File(photo, "image/jpeg") : (ActionResult)(null);
        }
    }
}

MVC4LOL/Controllers/ChampionJsonController.cs
using MVC4LOL.Models.ViewModels;
using MVC4LOL.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace MVC4LOL.Controllers
{
    [Authorize]
    public class ChampionJsonController : Controller
    {
        //TODO DELETE.
        //public ActionResult Index()
        //{ 
        //    MVC4LOLDb us = new MVC4LOLDb();
        //    var m = us.Champions.ToList();

        //    return Json(m, JsonRequestBehavior.AllowGet);
        //}
        private MVC4LOLDb db = new MVC4LOLDb();

        public ActionResult Details(Int32 championId)
        {
            return View("Details", championId);
        }

        public ActionResult DetailsJson(Int32 championId)
        {
            var model = new ChampionDetailsViewModel();

            model.Patches = db.PatchVersions.ToList();
            Int32 latestPatchId = model.Patches.OrderByDescending(o => o.Date).First().Id;
            model.SelectedPatchId = latestPatchId;

            model.Tags = db.Tags.Where(o => o.UserId == WebSecurity.CurrentUserId && o.ChampionId == championId).ToList();
            model.Champions = db.ChampionData.Where(o => o.ChampionId == championId).ToList();

            var jsonResult = Json(ChangeByteArrayToStringForModel(model), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public Object ChangeByteArrayToStringForModel(ChampionDetailsViewModel model)
        {

            List<ChampionDetailsViewModel> ml = new List<ChampionDetailsViewModel>();
            ml.Add(model);

            var res = ml.Select(o => new
            {
                Tags = o.Tags,
                Patches = o.Patches,
                Champions = o.Champions.Select(c => new
                {
                    Image = c.Image != null ? Convert.ToBase64String(c.Image) : String.Empty,
                    Armor = c.Armor,
                    ArmorPerLvl = c.ArmorPerLvl,
                    AttackSpeed = c.BaseAttackSpeed,
                    AttackSpeedPerLvl = c.AttackSpeedPerLvl,
                    Champion = c.Champion,
                    ChampionId = c.ChampionId,
                    Damage = c.Damage,
                    DamagePerLvl = c.DamagePerLvl,
                    Health = c.Health,
                    HealthPerLvl = c.HealthPerLvl,
                    HealthRegen = c.HealthRegen,
                    HealthRegenPerLvl = c.HealthRegenPerLvl,
                    Id = c.Id,
                    IP_Cost = c.IP_Cost,
                    MagicResist = c.MagicResist,
                    MagicResistPerLvl = c.MagicResistPerLvl,
                    Mana = c.Mana,
                    ManaPerLvl = c.ManaPerLvl,
                    ManaRegen = c.ManaRegen,
                    ManaRegenPerLvl = c.ManaRegenPerLvl,
                    MoveSpeed = c.MoveSpeed,
                    Name = c.Name,
                    PatchVersion = c.PatchVersion,
                    PatchVersionId = c.PatchVersionId,
                    Range = c.Range,
                    ReleaseDate = c.ReleaseDate,
                    RP_Cost = c.RP_Cost,
                    Title = c.Title,
                })
            });

            return res.First();
        }

        public ActionResult Index2()
        {
            return View();
        }

        public ActionResult IndexModel()
        {
            ChampionsViewModel model = new ChampionsViewModel();
            MVC4LOLDb us = new MVC4LOLDb();
            model.Champions = us.ChampionData.ToList();
            model.Patches = us.PatchVersions.ToList();
            model.Tags = us.Tags.Where(o => o.UserId == WebSecurity.CurrentUserId).ToList(); 

            var jsonResult = Json(ChangeByteArrayToStringForModel(model), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }
        
        public Object ChangeByteArrayToStringForModel(ChampionsViewModel model)
        {

            List<ChampionsViewModel> ml = new List<ChampionsViewModel>();
            ml.Add(model);

            var res = ml.Select(o => new
            {
                Tags = o.Tags,
                Patches = o.Patches,
                Champions = o.Champions.Select(c => new 
                            {
                                Image = c.Image != null ? Convert.ToBase64String(c.Image) : String.Empty,
                                Armor = c.Armor,
                                ArmorPerLvl = c.ArmorPerLvl,
                                AttackSpeed = c.BaseAttackSpeed,
                                AttackSpeedPerLvl = c.AttackSpeedPerLvl,
                                Champion = c.Champion,
                                ChampionId = c.ChampionId,
                                Damage = c.Damage,
                                DamagePerLvl = c.DamagePerLvl,
                                Health = c.Health,
                                HealthPerLvl = c.HealthPerLvl,
                                HealthRegen = c.HealthRegen,
                                HealthRegenPerLvl = c.HealthRegenPerLvl,
                                Id = c.Id,
                                IP_Cost = c.IP_Cost,
                                MagicResist = c.MagicResist,
                                MagicResistPerLvl = c.MagicResistPerLvl,
                                Mana = c.Mana,
                                ManaPerLvl = c.ManaPerLvl,
                                ManaRegen = c.ManaRegen,
                                ManaRegenPerLvl = c.ManaRegenPerLvl,
                                MoveSpeed = c.MoveSpeed,
                                Name = c.Name,
                                PatchVersion = c.PatchVersion,
                                PatchVersionId = c.PatchVersionId,
                                Range = c.Range,
                                ReleaseDate = c.ReleaseDate,
                                RP_Cost = c.RP_Cost,
                                Title = c.Title,
                            })
            });

            return res.First();
        }
    }
}

MVC4LOL/Views/Champion/CreateTag.cshtml
@model MVC4LOL.Models.EditTagsViewModel

@{
    ViewBag.Title = "";
}

<h2>Create Tag</h2>
<div>
     <img src="@Url.Action("GetPhotoLastPatch", new { photoId = Model.ChampionId})" />
</div>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>EditTagsViewModel</legend>

        @Html.HiddenFor(model => model.ChampionId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back", "Tags", "Champion", new { championID = Model.ChampionId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC4LOL/Views/Champion/Details.cshtml
@model MVC4LOL.Models.ViewModels.ChampionDetailsViewModel

@{
    ViewBag.Title = "Details";
}

@Scripts.Render("~/bundles/leveling")
<h2>Details</h2>

<script type="text/javascript">
    
    $(document).ready(function () {
        
        leveling.init();
        
    });

</script>

<fieldset>
    <legend>Champion</legend>

    @if (Model.Tags.Count == 0)
    {
        @Html.ActionLink("Add Tag", "CreateTag", "Champion", new { ChampionId = Model.Champions.First().ChampionId }, null);
    }
    else
    {    
        @Html.ActionLink("Tags", "Tags", "Champion", new { ChampionId = Model.Champions.First().ChampionId }, null);
    }
    
    @foreach (var patch in Model.Patches)
    {
        @Html.RadioButton("Radio" + @patch.Name, patch.Id) @patch.Name
    }

    @{Int32 selectedPatchId = 1; }
    
    <ul>
        @foreach (var a in Model.Tags){
        <li>@Html.DisplayName(a.Name)</li>
        }
    </ul>

    <div>
        <img src="@Url.Action("GetPhoto", new { photoId = Model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Id })" />
    </div>
    <input type="button" name="buttonLvlUp" id="buttonLvlUp" value="LvlUp" />
    <input type="button" name="buttonLvlDown" id="buttonLvlDown" value="LvlDown" />
    <label id="labelLvl" >1</label>

    <table>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Name)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Name)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Title)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Title)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ReleaseDate)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ReleaseDate)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).IP_Cost)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).IP_Cost)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).RP_Cost)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).RP_Cost)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Health)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Health)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).HealthPerLvl)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).HealthPerLvl)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).HealthRegen)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).HealthRegen)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).HealthRegenPerLvl)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).HealthRegenPerLvl)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Mana)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Mana)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ManaPerLvl)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ManaPerLvl)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ManaRegen)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ManaRegen)
                </div>
            </td>
        </tr>
         <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ManaRegenPerLvl)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ManaRegenPerLvl)
                </div>
            </td>
        </tr>
         <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Range)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Range)
                </div>
            </td>
        </tr>
         <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Damage)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Damage)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).DamagePerLvl)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).DamagePerLvl)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).AtkSpeed)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).AtkSpeed
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).AtkSpeedPerLvl)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).AtkSpeedPerLvl)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Armor)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).Armor)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ArmorPerLvl)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).ArmorPerLvl)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).MagicResist)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).MagicResist)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).MagicResistPerLvl)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).MagicResistPerLvl)
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                     @Html.DisplayNameFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).MoveSpeed)
                </div>
            </td>
            <td>
                <div class="display-field">
                    @Html.DisplayFor(model => model.Champions.First(o => o.PatchVersionId == Model.SelectedPatchId).MoveSpeed)
                </div>
            </td>
        </tr>
    </table>

    
    

    
    
</fieldset>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |*@
    @Html.ActionLink("Back to Champions", "Index2", "ChampionJson")
    @*@Html.ActionLink("Back to List", "Index")*@
</p>

MVC4LOL/Views/Champion/Tags.cshtml
@model MVC4LOL.Models.ViewModels.TagsViewModel

@{
    ViewBag.Title = "Tags";
}

<h2>@Model.Champion.Name Tags</h2>

<p>
    @Html.ActionLink("Add Tag", "CreateTag", "Champion", new { championId = Model.Champion.Id}, null) 
</p>
<div>
     <img src="@Url.Action("GetPhotoLastPatch", new { photoId = Model.Champion.Id})" />
</div>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tags.First().Name)
        </th>
        <th>
            Action
        </th>
    </tr>

@foreach (var item in Model.Tags) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |*@
            @Html.ActionLink("Delete", "DeleteTag", "Champion" , new { tagId = item.Id }, null)
        </td>
    </tr>
}
@Html.ActionLink("Back", "Details2", "Champion", new { championId = Model.Champion.Id}, null)

</table>